# Generated by Django 5.0.7 on 2024-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='tipo_documento',
            field=models.CharField(choices=[('0', 'Registro Civil'), ('1', 'Tarjeta Identidad'), ('2', 'Cedula Ciudadania'), ('3', 'Tarjeta Extranjeria'), ('4', 'Otro')], max_length=1, verbose_name='Tipo Documento'),
        ),
    ]
