# Generated by Django 5.0.7 on 2024-07-16 19:38

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eps', '0001_initial'),
        ('examen', '0001_initial'),
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('fecha_actual', models.DateField(verbose_name='Cita dada el dia')),
                ('fecha_cita', models.DateField(verbose_name='Cita para el dia')),
                ('hora_cita', models.TimeField(verbose_name='Hora Cita')),
                ('historia_clinica', models.CharField(max_length=20, verbose_name='Historia Clinica')),
                ('codigo_autorizacion', models.CharField(max_length=20, verbose_name='Codigo Autorizacion')),
                ('obsernaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_eps', to='eps.eps')),
                ('examen', models.ForeignKey(default='Examen', on_delete=django.db.models.deletion.CASCADE, related_name='cita_examen', to='examen.examen')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_paciente', to='paciente.paciente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_cita', 'hora_cita'],
                'unique_together': {('fecha_cita', 'hora_cita')},
            },
        ),
    ]
