# Generated by Django 5.0.7 on 2024-07-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cita', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('fecha_cita', 'hora_cita')},
        ),
    ]
